# Generated by Django 5.1.5 on 2025-02-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Amigos'), ('E', 'Enemigos'), ('N', 'Neutrales')], max_length=10)),
                ('personaje1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaje1', to='personajes.personaje')),
                ('personaje2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaje2', to='personajes.personaje')),
            ],
        ),
    ]
