# Generated by Django 5.1.5 on 2025-02-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dano_base', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('espada', 'Espada'), ('hacha', 'Hacha'), ('daga', 'Daga'), ('arco', 'Arco'), ('baston', 'Bastón')], max_length=10)),
                ('es_unica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('defensa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('V', 'Poción de vida'), ('A', 'Poción de ataque')], max_length=10)),
                ('potencia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dano', models.PositiveIntegerField()),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='equipamiento.arma')),
            ],
        ),
    ]
