# Generated by Django 5.1.5 on 2025-02-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipamiento', '0001_initial'),
        ('facciones', '0001_initial'),
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='personajes.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, default='personajes/default.jpg', null=True, upload_to='personajes/')),
                ('arma_equipada', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamiento.arma')),
                ('armadura_equipada', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamiento.armadura')),
                ('faccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facciones.faccion')),
                ('localizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localizaciones.localizacion')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='personaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='personajes.personaje'),
        ),
    ]
