# Generated by Django 5.1.6 on 2025-02-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='hp',
            field=models.IntegerField(default=100),
        ),
    ]
